package gui;

/**
 * Created by Bryant Gonzaga on 11/14/2016.
 */
public enum BuzzwordProperties
{
	//CSS PROPERTIES
	USERNAME_HOLDER_STYLE,
	SUB_HEADER_STYLE,
	LABEL_STYLE,
	GAME_MODE_MENU_TOOLTIP,
	TEXTFIELD_STYLE,
	LETTER_STYLE,
	HEADING_LABEL,
	WORKSPACE_HEADER_LABEL,
	BUTTON_STYLE
}
