package gui;

/**
 * Created by Bryant Gonzaga on 11/14/2016.
 */
public enum BuzzwordProperties
{
	//BUTTON TOOLTIPS
	LOGOUT_TOOLTIP,
	USERNAME_TOOLTIP,
	PASSWORD_TOOLTIP,
	GAME_MODE_MENU_TOOLTIP,
	NEW_ACCOUNT_TOOLTIP,
	HOME_TOOLTIP,
	//CSS PROPERTIES
	BACKGROUND_STYLE,
	TEXT_PANE_BACKGROUND,
	SUB_HEADER_STYLE,
	LABEL_STYLE,
	TEXTFIELD_STYLE,
	LETTER_STYLE,
	BUTTON_STYLE,
	PLAY_BUTTON,
	PAUSE_BUTTON,
	//LABEL TEXT
	HEADING_LABEL,
	WORKSPACE_HEADER_LABEL
	//
}
